export const mockWeather = {
  request: {
    type: "City",
    query: "New York, United States of America",
    language: "en",
    unit: "m",
  },
  location: {
    name: "New York",
    country: "United States of America",
    region: "New York",
    lat: "40.714",
    lon: "-74.006",
    timezone_id: "America/New_York",
    localtime: "2023-04-01 05:32",
    localtime_epoch: 1680327120,
    utc_offset: "-4.0",
  },
  current: {
    observation_time: "09:32 AM",
    temperature: 14,
    weather_code: 122,
    weather_icons: [
      "https://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png",
    ],
    weather_descriptions: ["Overcast"],
    wind_speed: 4,
    wind_degree: 10,
    wind_dir: "N",
    pressure: 1006,
    precip: 0,
    humidity: 74,
    cloudcover: 100,
    feelslike: 12,
    uv_index: 1,
    visibility: 16,
    is_day: "no",
  },
};
